sudo: required
dist: xenial
matrix:
  include:
    - language: python
      python: 3.9
      script:
        - cd scripts/tests; pytest
      env:
        - PYTHONPATH=..
    - language: scala
      scala: 2.12.13
