package org.clulab.linnaeus.model.fmt1.graph.eidos

import org.clulab.linnaeus.model.fmt1.graph.GraphNetwork
import org.clulab.linnaeus.model.fmt1.graph.Indexer

class EidosNoMetaNetwork(id: Int = 0, path: String = "") extends GraphNetwork[
  Long,
  Long, EidosNoMetaNode,
  Long, EidosEdge
](id) {
  /**
    * Networks in Eidos format have nodes (and implied edges) that are distinct based on
    * their very existence in the hierarchy.  To assure this, they are all given unique IDs
    * that are generated by these indexers.
    */
  val nodeIndexer = new Indexer()
  val edgeIndexer = new Indexer()

  override def newRootNode(): EidosNoMetaNode = new EidosNoMetaNode(nodeIndexer.next, EidosNetwork.ROOT_NODE)

  override def newRootEdge() = new EidosEdge(edgeIndexer.next, EidosNetwork.ROOT_EDGE)
}
